ssl fixed
probably broken since:
b5778f5f14182444971c0468c97c1e97dbbe4e99
Ralf Wiebicke <ralf.wiebicke@exedio.com>
Sat Feb 10 12:40:34 2018 +0100
update javax.mail to 1.6.0

did fail with:
Testcase: testSendMail(com.exedio.sendmail.MailSenderTest):	Caused an ERROR
javax.mail.NoSuchProviderException: No provider for smpts
java.lang.RuntimeException: javax.mail.NoSuchProviderException: No provider for smpts
   at com.exedio.sendmail.MailSender.sendMails(MailSender.java:253)
   at com.exedio.sendmail.MailSenderTest.testSendMail(MailSenderTest.java:630)
Caused by: javax.mail.NoSuchProviderException: No provider for smpts
   at javax.mail.Session.getProvider(Session.java:514)
   at javax.mail.Session.getTransport(Session.java:712)
   at javax.mail.Session.getTransport(Session.java:693)
   at com.exedio.sendmail.MailSender.sendMails(MailSender.java:249)